### ISSUE TITLE
hybrid-cloud-patterns.io seems deprecated for validatedpatterns.io

### ISSUE THREAD

**Issue by adelton** [k8s-operatorhub/community-operators#3485]
The site https://hybrid-cloud-patterns.io/ which is mentioned for example at https://operatorhub.io/operator/patterns-operator says "Redirecting you to the new Validated Patterns site" and redirects to https://validatedpatterns.io/.

The occurrences of "hybrid-cloud-patterns.io", like those found by https://github.com/search?q=org%3Ak8s-operatorhub+hybrid-cloud-patterns.io&type=code, should likely be changed to the new location of that activity.

**Comment by adelton** [comment]
For the record, the URL is wrong on https://operatorhub.io/operator/patterns-operator but when installing the Validated Patterns Operator (version 0.0.32) from OperatorHub via my OpenShift cluster console, the

> Deploys and manages architecture patterns from https://validatedpatterns.io

is shown.

Does this mean this repo is not the correct upstream for this operator?

**Comment by Denney-tech** [comment]
I'm not a maintainer here, so take this with a grain of salt.

This is an upstream issue; it's their responsibility to submit PR's for new versions of their operator. The one in the community catalog hasn't been updated since last year. The version here is 0.0.1, and upstream is tagged up to 0.0.33. They don't have any CI setup to automatically submit PR's here like some others do (like the awx-operator for e.g.). Versioned content is generally expected to be immutable, so even if the upstream submits updated PR's, I wouldn't necessarily expect or allow the 0.0.1 version to be changed retroactively. You would just install or upgrade to the latest version, and the documentation would reflect the updated descriptions in the latest version (which your particular issue is already fixed upstream).

You might check with @beekhof if he has any comment on the matter since he submitted the initial version here, and appears to still work on Validated Patterns repositories. Otherwise submit an issue upstream.

**Comment by adelton** [comment]
Thanks, I filed https://github.com/validatedpatterns/patterns-operator/issues/151 now.

**Comment by adelton** [comment]
I don't mind this issue getting closed but I object to the *completed* reason / resolution that the bot added. It should be something like NOTABUG / WONTFIX / whatever this project uses.
