### ISSUE TITLE
Build Bundles Failure

### ISSUE THREAD

**Issue by jvpasinatto** [k8s-operatorhub/community-operators#5242]
Hi,

Both of these actions:
https://github.com/k8s-operatorhub/community-operators/actions/runs/11660462075/job/32465164000
https://github.com/k8s-operatorhub/community-operators/actions/runs/11660142590/job/32462378032
failed in build bundles action with the same error:
`TASK [build_operator_version_bundle : Fail if directory doesn't exists] ********
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Directory ''/tmp/operator-test/operators/opentelemetry-operator/0.16.0/tests/scorecard/'' specified in ''operators.operatorframework.io.test.config.v1'' doesn''t exists !!! '
`
 As result, release process was not completed and bundles are not appearing in operatorhub.io.

Can you help?
Thanks.

**Comment by iamjoemccormick** [comment]
I encountered the same [workflow error](https://github.com/k8s-operatorhub/community-operators/actions/runs/11669670792/job/32492729352) and it seems [all commits](https://github.com/k8s-operatorhub/community-operators/commits/main/) to the main branch since November 1st are also encountering the same error. Perhaps some requirements changed around the bundle format? Though I would have expected the CI wouldn't have allowed my PR to be merged if that was the case.

**Comment by tomasbakk** [comment]
Hello. We are aware of this issue and currently it is under investigation. I will update you once we have more information. Thank you.

**Comment by tomasbakk** [comment]
@jvpasinatto @iamjoemccormick Hi guys. The issue was resolved. Latest manual release fixed the broken operator. Now we will proceed with syncing the operators that were affected during the window.
